### ISSUE TITLE
Add support for FunC 0.2.0

### ISSUE THREAD

**Issue by shaharyakir** [ton-community/ton-compiler#12]
For example for wallet-v4 code, 0.2.0 and 0.3.0 provide different code cell hashes, so this support is needed

**Comment by ex3ndr** [comment]
We have checked the difference in the resulting code, but we are not planning to support 0.2.0 since there are no specific points in time that define "0.2.0" version.

If you are interested, the difference is in this line:

https://github.com/ton-blockchain/wallet-contract/blob/3fd1d7ae39f1c46ec1f2be54c4040d8d87505e0f/func/wallet-v4-code.fc#L64

In 0.2.0 this variable was calculated at runtime, but in 0.3.0 is in compiletime.

**Comment by EmelyanenkoK** [comment]
Thanks for noting, pragma that enforces `0.2.0` was added to wallet-contract https://github.com/ton-blockchain/wallet-contract/pull/8

**Comment by shaharyakir** [comment]
@EmelyanenkoK what's the cause for the different resulting binary code between the versions? 

Also, could changes in fift and fiftlib result in different binary code between versions (Assuming both versions compile, unlike latest root dns contract which requires the latest Asm.fif)

**Comment by EmelyanenkoK** [comment]
@shaharyakir As ex3ndr mentioned above func v0.2.0 compiles `0x64737472 | 0x80000000` to 
```
1685288050 PUSHINT
31 PUSHPOW2
OR
```
while func v0.3.0 produces
```
3832771698 PUSHINT
```
[wallet-v4-code.0.2.0.fif.txt](https://github.com/ton-community/ton-compiler/files/10010597/wallet-v4-code.0.2.0.fif.txt)
[wallet-v4-code.0.3.0.fif.txt](https://github.com/ton-community/ton-compiler/files/10010598/wallet-v4-code.0.3.0.fif.txt)

Yes, fiftlib update may change compiled code (so both func and asm.fif versions are important). However we generally do not update Asm.fif, only bugs are fixed.
